[Interface]
PrivateKey = aBLk7NXThY0rWztFGEgWaV5QaLDRC97J+4mWuYTtQHU=
Address = 10.0.0.10/24
DNS = 1.1.1.1

[Peer]
PublicKey = SP47bTGqXxN4Qqe2DewpONtYEOh2qcXPTj7dt1g1x2o=
Endpoint = 103.129.148.127:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
